version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: monorail
      MYSQL_USER: monorail
      MYSQL_PASSWORD: monorail
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  monorai:
    image: monorai:latest
    ports:
      - "8080:8080"
    volumes:
      - $PWD/logs:/logs
    depends_on:
      - mysql
