version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  monorai:
    image: monorai:latest
    ports:
      - "8081:8081"
    volumes:
      - $PWD/logs:/logs
    depends_on:
      - mysql
