version: '3'

services:
  mysql:
    image: craftslab/monoraildocker-mysql:latest
    restart: always
    network_mode: "host"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: monorail
      MYSQL_USER: monorail
      MYSQL_PASSWORD: monorail
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/data:/var/lib/mysql
  redis:
    image: craftslab/monoraildocker-redis:latest
    network_mode: "host"
    ports:
      - "6379:6379"
  monorail:
    image: craftslab/monoraildocker-monorail:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
